### ISSUE TITLE
使用该项目在 Read the Docs 上 build 的时候，会出现错误。

### ISSUE THREAD

**Issue by haokanjiang** [Revolution1/Flask-WhooshAlchemyPlus#5]
使用该项目在 Read the Docs 上 build 的时候，会出现以下错误。
```
Collecting Flask-WhooshAlchemyPlus==0.7.5 (from -r requirements.txt (line 28))
  Using cached Flask-WhooshAlchemyPlus_V0.7.5.tar.gz
    Complete output from command python setup.py egg_info:
    error in Flask-WhooshAlchemyPlus setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in blinker (>=1.3) at  (>=1.3)
```

根据错误提示需要将 `requirements.txt` 的 `(>=version) ` 改成 `==version` 。

打包时又出现以下错误：

``` 
$ python setup.py sdist

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    test_suite='test.test_all',
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 259, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python2.7/distutils/dist.py", line 1220, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python2.7/distutils/versionpredicate.py", line 113, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '==1.3'

```

这个错误我不太理解，但是对照 `Flask-WhooshAlchemy` 这个项目的 `setup.py` 文件，发现 `classifiers` 多了一个 `requires` 属性。

删除该属性后，能正常打包。

在 `Read the Docs` 上也能正常 build 了。

但需要将编译后的源码 push 到我项目中。

**Comment by Revolution1** [comment]
我还没有用过 readthedocs，这里的 build 是怎样一个过程？我把 requiresments.txt 改成这样是因为 #2 。pip 依赖的写法的确很迷，我还没找出正确的方法。
